services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: globalgo
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    container_name: springboot
    build:
      context: ./GlobalGo/Backend/GlobalGo
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/globalgo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./GlobalGo/Frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data:
